# Generated by Django 5.2.6 on 2025-09-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='dailystock',
            name='starting_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
